version: '3.8'
services:
  db:
      container_name: postgres
      image: postgres
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: pass
        POSTGRES_DB: postgres
      ports:
      - "5432:5432"
      volumes:
      - db-data:/var/lib/postgresql/data

  geant4help:
    container_name: geant-web
    image: geant4help
    depends_on:
    - db
    links:
    - db
    restart: always
    ports:
    - "8080:8080"
volumes:
  db-data:
    driver: local